package Telas;

import CadastroCliente.UsuarioDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class Inicio extends javax.swing.JPanel {

    private TelaInicial1 frame;

    public Inicio(TelaInicial1 frame) {
        initComponents();
        this.frame = frame;
      
    }

    //Colocando o background (imagem)
    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        try {
            //carregando a imagem de fundo
            Image imagens = ImageIO.read(
                    new File(getClass().
                            getResource("/imagens/Tela1.png").
                            getFile()));

            //redimen. uma imagem
            imagens = imagens.getScaledInstance(310, 611,
                    Image.SCALE_DEFAULT);

            //"pintando" a imagem no painel
            g.drawImage(imagens, 0, 0, this);

        } catch (IOException ex) {
            System.err.println("o arquivo esta corrompido");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botãoCad = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        botãoCad.setBackground(new java.awt.Color(255, 255, 255));
        botãoCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botãoCad.setText("Faça seu cadastro");
        botãoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoCadActionPerformed(evt);
            }
        });

        jLabel7.setText("CPF");

        cpfTxt.setText("digite.....");
        cpfTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpfTxtMouseClicked(evt);
            }
        });
        cpfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Senha");

        senhaTxt.setText("Senha");
        senhaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senhaTxtMouseClicked(evt);
            }
        });
        senhaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTxtActionPerformed(evt);
            }
        });

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setText("VAMOS LÁ");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(senhaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Login))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(botãoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(botãoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

        UsuarioDAO dao = new UsuarioDAO();
        if (dao.checkLogin(cpfTxt.getText(), new String(senhaTxt.getPassword()))) {
            frame.trocarPainel(new MenuConta(frame, cpfTxt.getText()));
            Login.setOpaque(false);
            Login.setContentAreaFilled(false);
            Login.setBorderPainted(false);
        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta!");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void cpfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTxtActionPerformed

    private void botãoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoCadActionPerformed
        frame.trocarPainel(new MenuCad(frame));
    }//GEN-LAST:event_botãoCadActionPerformed

    private void senhaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTxtActionPerformed

    private void cpfTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpfTxtMouseClicked

        //Tirando o que esta escrido dentro do CpfText
        if (cpfTxt.getText().equals("digite.....")) {
            cpfTxt.setForeground(new Color(0, 0, 0));
            cpfTxt.setBackground(new Color(245, 245, 245));
            cpfTxt.setText("");
        }
    }//GEN-LAST:event_cpfTxtMouseClicked

    private void senhaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senhaTxtMouseClicked
          senhaTxt.setEchoChar('*');

        //Tirando o que ta escrito do Passoword e colocando cor ao fundo
        if (senhaTxt.equals("*")) {
            senhaTxt.setForeground(new Color(0, 0, 0));
            senhaTxt.setBackground(new Color(245, 245, 245));
            senhaTxt.setText("");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_senhaTxtMouseClicked

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed

        //Classe de verificação de login       
        UsuarioDAO dao = new UsuarioDAO();
        if (dao.checkLogin(cpfTxt.getText(), new String(senhaTxt.getPassword()))) {
            frame.trocarPainel(new MenuConta(frame, cpfTxt.getText()));
        } else {
            JOptionPane.showMessageDialog(null, (Color.red) + "Senha incorreta!");

        }

    }//GEN-LAST:event_LoginKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton botãoCad;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField senhaTxt;
    // End of variables declaration//GEN-END:variables

}
