package Telas;

import CadastroCliente.CadastroDAO;
import Cliente.Cliente;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class MenuCad extends javax.swing.JPanel {

    private final TelaInicial1 frame;

    //*** Definição de conta ***//
    private boolean definicaoConta = false;
    private String Corrente;

    CadastroDAO cadastroDAO = new CadastroDAO();

    //Gerador de codigo de segunraça //
    public int codigoSeg() {
        Random sorteia = new Random();
        int valor = sorteia.nextInt(0, 4);
        int sorte;
        if (valor > 1) {
            sorte = sorteia.nextInt(48, 57);
        } else {
            sorte = sorteia.nextInt(97, 122);
        }
        return sorte;
    }

    //Construtor do MenuCadastro
    public MenuCad(TelaInicial1 frame) {
        initComponents();
        this.frame = frame;
    }

    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        try {
            //carregando a imagem de fundo
            Image imagens;
            imagens = ImageIO.read(
                    new File(getClass().
                            getResource("/imagens/Tela3.png").
                            getFile()));

            //redimencionamento da imagem
            imagens = imagens.getScaledInstance(310, 611,
                    Image.SCALE_DEFAULT);

            //alocando a imagem no painel
            g.drawImage(imagens, 0, 0, this);

        } catch (IOException ex) {
            System.err.println("o arquivo esta corrompido");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomeCad = new javax.swing.JTextField();
        CpfCad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DDCad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SenhaCad = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Senha2Cad = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        Vcad = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        setPreferredSize(new java.awt.Dimension(310, 600));

        jLabel3.setText("Olá seja bem vindo vamos iniciar seu cadastro");

        jLabel4.setText("*Nome completo");

        NomeCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomeCadMouseClicked(evt);
            }
        });
        NomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCadActionPerformed(evt);
            }
        });

        CpfCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CpfCadMouseClicked(evt);
            }
        });
        CpfCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfCadActionPerformed(evt);
            }
        });

        jLabel5.setText("*CPF");

        DDCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DDCadMouseClicked(evt);
            }
        });

        jLabel6.setText("*Data de nascimento");

        SenhaCad.setText("jPasswordField1");
        SenhaCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SenhaCadMouseClicked(evt);
            }
        });

        jLabel7.setText("*Escolha sua senha ");

        Senha2Cad.setText("jPasswordField2");
        Senha2Cad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Senha2CadMouseClicked(evt);
            }
        });

        jLabel8.setText("*Confirme sua senha");

        jCheckBox1.setText("Conta corrente");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Conta poupança");

        jButton1.setText("Tudo certinho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Vcad.setText("voltar");
        Vcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VcadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBox2))
                        .addComponent(DDCad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Senha2Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Vcad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DDCad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(SenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Senha2Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Vcad)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CpfCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpfCadActionPerformed

    private void NomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Primeiro definição de conta corrente ou poupança 
        if (definicaoConta == true) {
            Corrente = "corrente";
        } else {
            Corrente = "poupanca";
        }

        //Cliente alocando as infoermaçoes do cadastro nome,cpf,Data de nascimento e sua Senha 
        Cliente cliente = new Cliente();
        cliente.setNome(NomeCad.getText());
        cliente.setCPF(CpfCad.getText());
        cliente.setValor_conta(0);
        cliente.setConta(Corrente);
        cliente.setCodigo_segurança(codigoSeg());
        cliente.setData_nascimento(DDCad.getText());
        String senha = new String(SenhaCad.getPassword());

        if (NomeCad.getText().equalsIgnoreCase("") || CpfCad.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Informaçoes invalidas");
        } else {
            cadastroDAO.save(cliente);
            cadastroDAO.update(cliente);
            frame.trocarPainel(new MenuConta(frame, CpfCad.getText()));
        }
        try {
            cliente.setSenha_conta(Integer.parseInt(senha));

        } catch (NumberFormatException ex) {

        }

        //Salvando dentro do Banco de Dados
        //Atualiazando dentro do Banco de Dados 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void VcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VcadActionPerformed
        frame.trocarPainel(new Inicio(frame));
    }//GEN-LAST:event_VcadActionPerformed

    private void NomeCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomeCadMouseClicked
        NomeCad.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_NomeCadMouseClicked

    private void CpfCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CpfCadMouseClicked
        CpfCad.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_CpfCadMouseClicked

    private void DDCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DDCadMouseClicked
        DDCad.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_DDCadMouseClicked

    private void SenhaCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenhaCadMouseClicked
        SenhaCad.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_SenhaCadMouseClicked

    private void Senha2CadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Senha2CadMouseClicked
        Senha2Cad.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_Senha2CadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CpfCad;
    private javax.swing.JTextField DDCad;
    private javax.swing.JTextField NomeCad;
    private javax.swing.JPasswordField Senha2Cad;
    private javax.swing.JPasswordField SenhaCad;
    private javax.swing.JButton Vcad;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
