package Telas;

import CadastroCliente.CadastroDAO;
import CadastroCliente.Trasferencia;
import Cliente.Cliente;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javaComBanco.Conexao;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class TransTela extends javax.swing.JPanel {

    private final TelaInicial1 frame;
    private String cpf;

    static ResultSet rs;

    CadastroDAO cadastroDAO = new CadastroDAO();
    Cliente cliente = new Cliente();
    Cliente cliente2 = new Cliente();

    //Classe de conexão e obtenção dela
    Conexao c = new Conexao();
    Connection conexao = c.obterConexao();

    public static void verifSaldo(double val, Cliente cliente, CadastroDAO cadastroDAO) {

        //verificação de saldo do usuario dono da conta
        if (val <= cliente.getValor_conta()) {
            cliente.setValor_conta(cliente.getValor_conta() - val);
            cadastroDAO.updateSaldo(cliente);
            JOptionPane.showMessageDialog(null, "Trasferencia completa!!!");

        } else {
            JOptionPane.showInternalMessageDialog(null, "Valor inválido");

        }
    }
    //165.356.777-44
    //Construtor passando o cpf do frame anterior (_cpf, frame MenuConta)

    public TransTela(TelaInicial1 frame, String _cpf) {
        initComponents();
        this.frame = frame;
        this.cpf = _cpf;
    }

    TransTela(TelaInicial1 frame) {
        initComponents();
        this.frame = frame;
    }

    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        try {
            //carregando a imagem de fundo
            Image imagens = ImageIO.read(
                    new File(getClass().
                            getResource("/imagens/Tela4.png").getFile()));

            //redimen. uma imagem
            imagens = imagens.getScaledInstance(310, 611,
                    Image.SCALE_DEFAULT);

            //"pintando" a imagem no painel
            g.drawImage(imagens, 0, 0, this);

        } catch (IOException ex) {
            System.err.println("o arquivo esta corrompido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CpfTrasfe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ValorTrafe = new javax.swing.JTextField();
        ButtomTrafe = new javax.swing.JButton();

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CPF");

        CpfTrasfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfTrasfeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor da transferencia");

        ButtomTrafe.setText("Transferir");
        ButtomTrafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomTrafeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ValorTrafe, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(CpfTrasfe, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(ButtomTrafe)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CpfTrasfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValorTrafe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(ButtomTrafe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CpfTrasfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfTrasfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpfTrasfeActionPerformed

    private void ButtomTrafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomTrafeActionPerformed

        try {

            String SQL = ("SELECT * FROM aprix.cliente"
                    + " where cpf = '" + cpf + "'");

            PreparedStatement pstm = conexao.prepareStatement(SQL);
            rs = pstm.executeQuery();

            //passar a query entre parenteses. stmt.executeQuery(SQL) por exemplo : String SQL = "select * from tabela where cpf = '"+ cpfInformado +"'
            if (rs == null) {
                System.out.println("ResultSet null");
            }

            while (rs.next()) {
                cliente.setValor_conta(rs.getDouble("valor_conta"));
                cliente.setCPF(rs.getString("cpf"));
            }
        } catch (SQLException ex) {
            System.out.print("Erro: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

        //Cliente pra quem ta sendo trasferido (cliente2)
        try {
            String SQL = ("SELECT * FROM aprix.cliente"
                    + " where cpf = '" + CpfTrasfe.getText() + "'");

            PreparedStatement pstm = conexao.prepareStatement(SQL);
            rs = pstm.executeQuery();

            //passar a query entre parenteses. stmt.executeQuery(SQL) por exemplo : String SQL = "select * from tabela where cpf = '"+ cpfInformado +"'
            if (rs == null) {
                System.out.println("ResultSet null");
            }

            while (rs.next()) {
                cliente2.setCPF(rs.getString("cpf"));
                cliente2.setValor_conta(rs.getDouble("valor_conta"));
                cliente2.setNome(rs.getString("nome"));
            }
                                         
        } catch (SQLException ex) {

            System.out.print("Erro: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
        
         int i =   JOptionPane.showConfirmDialog(null,"Trasferencia sera feita para :" + cliente2.getNome());
                           
         if (i== JOptionPane.YES_OPTION){     
        //Passando o parementrto de valor_conta de String para Double
        Double valtrasfe = Double.parseDouble(ValorTrafe.getText());
        Double upp2 = valtrasfe + cliente2.getValor_conta();
        cliente2.setValor_conta(upp2);
        verifSaldo(valtrasfe, cliente, cadastroDAO);
        cadastroDAO.updateSaldoCliente2(cliente2);      
        frame.trocarPainel(new MenuConta(frame, cpf));
         }
         else{
        JOptionPane.showMessageDialog(null, "Traferencia cancelada");
             frame.trocarPainel(new MenuConta(frame, cpf));
}
         
        
    }//GEN-LAST:event_ButtomTrafeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        frame.trocarPainel(new MenuConta(frame, cpf));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtomTrafe;
    private javax.swing.JTextField CpfTrasfe;
    private javax.swing.JTextField ValorTrafe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
